### ISSUE TITLE
CID salesteam mobile 

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#16]
Remove the contact information from the header when the site switches to mobile.

Center the logo vertically and horizontally.

Fix "Shipping" Section under Documents. Aligned too far left.

Enlarge all text under 30px by 2-4 pixels. (use best judgement for headlines/links/body copy)

**Comment by travishathaway** [comment]
@loreguerra 

I've fixed the header.  I have the same questions about this issue as the one about felixinstruments: https://github.com/travishathaway/travazine/issues/18

**Comment by loreguerra** [comment]
The contact information still shows up in the header on mobile.

Yes, all text should be a couple points larger.

Here is a screenshot of what I see.

![photo apr 19 1 01 41 pm](https://cloud.githubusercontent.com/assets/16310498/14653745/49148fdc-062f-11e6-905c-968289b6f8a3.png)

**Comment by travishathaway** [comment]
@loreguerra 

Fixed the misaligned "Shipping" section.  For the updates to the header, those will be included in the next round of updates to the production server.
