### ISSUE TITLE
Distributors dropdown

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#19]
Add 15px to the right of the dropdown menu to fix margin issue.

<img width="220" alt="screen shot 2016-04-18 at 12 37 42 pm" src="https://cloud.githubusercontent.com/assets/16310498/14617268/6fdde6ea-0562-11e6-82bc-db892ea8a162.png">

**Comment by travishathaway** [comment]
@loreguerra 

Fixed it.  You can see it in action on the staging site.

**Comment by loreguerra** [comment]
Cleared cache, not seeing the change on either site.

**Comment by travishathaway** [comment]
@loreguerra 

Looks like I missed it on CID.  I have fixed it there and it is on staging.

**Comment by loreguerra** [comment]
Weird. I'm still seeing it without the extra padding on all the sites, cache cleared.

**Comment by travishathaway** [comment]
![drop_down_menu](https://cloud.githubusercontent.com/assets/718726/14690264/9caf74be-074b-11e6-855e-fd3aa7bebf99.png)

@loreguerra 

Just so we're on the same page, the image above is how we need it, correct?  Notice how the drop down menu is perfectly aligned with the first letter of the menu item from which it originates.

Thanks.

**Comment by loreguerra** [comment]
That is very nice.

This is what I'm talking about.


![screen shot 2016-04-20 at 2 22 41 pm](https://cloud.githubusercontent.com/assets/16310498/14691009/cec45fca-0703-11e6-827f-758b25fcd2af.jpg)

**Comment by travishathaway** [comment]
@loreguerra 

Beautiful illustration!  I have increased the width of the drop down menu giving us more room and the desired layout.  Please let me know if it is acceptable.

**Comment by loreguerra** [comment]
It looks great. Thank you.
