### ISSUE TITLE
Change "email" link on staff page

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#23]
Needs to read "Email"

**Comment by travishathaway** [comment]
@loreguerra 

Fixed it.

**Comment by loreguerra** [comment]
Not seeing the change on either staging site.

**Comment by loreguerra** [comment]
The lowecase "e" in email is actually live on CID, which I think is unfortunate.

I went to delete someone's email and it still says "email" but the mailto is blank. It'd be nice to be able to have emails for some people and none for others without a mandatory blank placeholder. @travishathaway

**Comment by travishathaway** [comment]
@loreguerra 

This has been fixed on both the production site the staging sites.

**Comment by loreguerra** [comment]
Looks great on the live CID site, but the stage felix site now has no emails at all.

**Comment by travishathaway** [comment]
@loreguerra 

Thanks for catching that.  I have fixed it on the staging sites.

**Comment by loreguerra** [comment]
Thank you. I deleted an email but the link still shows up. Please see Brien Schultz here: https://stage.felixinstruments.com/about/

**Comment by travishathaway** [comment]
@loreguerra 

Thanks for catching that.  I have fixed it, and it is on the staging sites for you to verify.

**Comment by loreguerra** [comment]
Great! That works on the staging sites and I made an edit to the order of the Tour gallery but now nothing shows up in that section or the one below: https://stage.cid-inc.com/about/

**Comment by travishathaway** [comment]
@loreguerra 

Looks like this happens because the top level "About" item's url gets switched to "about".  When this happens Mezzanine wants to render this page instead of the one nested underneath it "Who We Are".

I fixed it on staging.  If that happens again, just make sure the top level "About"'s url field isn't "about".

**Comment by loreguerra** [comment]
got it. Thanks!
