### ISSUE TITLE
Mobile sites

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#49]
Disable images in Product Detail Page tabs. They are not resizing with the layout properly. Both sites.

<img width="721" alt="screen shot 2016-04-20 at 12 55 18 pm" src="https://cloud.githubusercontent.com/assets/16310498/14688375/28ed68d2-06f7-11e6-9699-3168cd7a41e4.png">

**Comment by travishathaway** [comment]
@loreguerra 

This is fixed. You can see it on the staging sites.

**Comment by loreguerra** [comment]
The video on the F-750 page (theory of operation) is massive on mobile. Is there a way to have it resize?

**Comment by loreguerra** [comment]
I'm also still not seeing the images disabled. Cleared cache on my phone.

**Comment by travishathaway** [comment]
@loreguerra 

Regarding the large image for the video placeholder, all you need to do is use our old friend "img-responsive" on the image by adding that as a class.  There are other images contained within the tabs that are also causing this issue with the layout.  This should be a suitable solution for those as well.

Regarding, the issue of the images being disabled on mobile, I'm pretty confused here.  The mobile version of the product detail page does not have any tabs on it.   Can you please attach a screen shot of what you are talking about?

**Comment by loreguerra** [comment]
I thought that might work!

Also, sorry for saying tabs. I meant the dropdown that the tabs become on mobile.

Here is a screenshot. Once I add those tags in, it should be fine. BUT I have now discovered that the dropdown links (specs, features, etc) do not work on Felix mobile.

![photo apr 21 9 38 45 am](https://cloud.githubusercontent.com/assets/16310498/14717202/1383adf4-07a5-11e6-85ce-47aaa2b3a076.png)

**Comment by loreguerra** [comment]
Also, now we don't need to disable those images. Just make sure the above links work!

**Comment by travishathaway** [comment]
@loreguerra 

I tested the accordion links ("Features", "Sepcifications", "Use Cases") and they work for me on my Samsung Galaxy S5.  I also used the Chrome dev tools in Iphone 6 mode, and they also work there.

Am I looking at the wrong thing?

**Comment by loreguerra** [comment]
No, you're looking at the correct links. They don't work on my phone for some reason.

**Comment by loreguerra** [comment]
I tried on another iPhone 5 here and an iPhone 6 and the links aren't working. Weird since they work for CID.
