### ISSUE TITLE
Numbers in green parenthesis are not updating when you filter by produc

### ISSUE THREAD

**Issue by JudithEdwards** [travishathaway/travazine#8]
https://cid-inc.com/applications/?product=136

**Comment by loreguerra** [comment]
@travishathaway

**Comment by travishathaway** [comment]
This has been fixed. Changes are on the live site

**Comment by JudithEdwards** [comment]
Unfortunately this still isn't working right. 

When you search by a product, you should get all of the possible application materials associated with it. If you search by the 110 for example, you see that there are 4 webinars and 43 publications, but the full results show 74 (which doesn't add up if there are 4 webinars and 43 publications). Then when you click on the publications, you see 165 results. The whole thing is a bit wonky. Let us know if you need further clarification on how we want this to work.

**Comment by travishathaway** [comment]
@JudithEdwards  and @loreguerra 

Thanks for bringing this up.  I will admit, the search is a bit wonky right now.  This stems from the fact that we are attempting to return four different content types via a single search. Here are the four content types we currently allow users to search:

- Publications (these are "Supporting Science", "White Papers", "Publication")
- Infographics
- Case Studies
- Embedded Content ("Video", and "Webinar")

The big reason for the number mismatch on the results is that I always return a homogeneous result set.  This means that items returned in the search are always of a specific type (e.g. Publications).  It is important to do this because otherwise you might confuse users viewing search results.

### Proposed Solution: Segregating the Search Page
The easiest way to convey to the user that they have the ability to search among our defined content types would be adding a navigation menu at the top that correspond the respective  content types. This means we would segregate the search page along the various content types we have defined.

We would have the following as navigation items on the search page:

- Publications (might be a little confusing considering a Publication can be classified as a Publication, maybe you have a better suggestion)
- Infographics
- Case Studies
- Videos and Webinars

When a user first visits the page, they will by default be searching everything in our "Publication" content type (this will be the active navigation tab). Here, they will be able to drill down by "Publication" category ("White Paper", "Supporting Science", "Publication", etc.) or by "Product" and "Field of Study". 

If the user wants to then search "Videos and Webinars", all they need to do is click the appropriate navigation tab, and begin.  Using this method also means we have the flexibility to categorize other contents types like we currently do with "Publications".

I think this will be the best way to organize the Applications page, and it will also be very simple for me to implement.

**Comment by JudithEdwards** [comment]
Hi Travis, 

A couple more things on this. The publications should be listed in order of data, with the newest publications listed first. 

Thanks,
Judith
